server:
  port: 7001
spring:
  application:
    name: eureka-config-server
  cloud:
    config:
      server:
        git:
          uri: http://git.oschina.net/didispace/SpringCloud-Learning/
          searchPaths: spring_cloud_in_action/config-repo
          username:
          password:
