version: '3'
services:
  eureka-server1:
    image: eureka-server1:v1
    container_name: eureka-server1
    build:
      context: ./eureka-server1/
      dockerfile: Dockerfile
    networks:
      - spring-cloud-netflix_eureka-net
  eureka-server2:
    image: eureka-server2:v1
    container_name: eureka-server2
    build:
      context: ./eureka-server2/
      dockerfile: Dockerfile
    networks:
      - spring-cloud-netflix_eureka-net
  eureka-client:
    image: eureka-client:v1
    container_name: eureka-client
    build:
      context: ./eureka-client/
      dockerfile: Dockerfile
    networks:
      - spring-cloud-netflix_eureka-net
  eureka-geteway:
    image: eureka-geteway:v1
    container_name: eureka-geteway
    build:
      context: ./eureka-gateway/
      dockerfile: Dockerfile
    ports:
      - 5555:5555
    depends_on:
      - eureka-client
    networks:
      - spring-cloud-netflix_eureka-net
networks:
  spring-cloud-netflix_eureka-net:
    external: true