server:
  port: 8080
eureka:
  instance:
    appname: eureka-client
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 2000
  ReadTimeout: 2000
