server:
  port: 8080
eureka:
  client:
    registry-fetch-interval-seconds: 3
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
logging:
  level:
    root: info
  pattern:
    console: "%d %clr(%-5p) %clr(${PID:-}){magenta} --- [%t] %clr(%c{10}.%M){cyan} \\(%file:%line\\) %m%n"