server:
  port: 8080
eureka:
  instance:
    appname: eureka-client
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
feign:
  hystrix:
    enabled: true
# Hystrix默认的超时时间是1秒，如果超过这个时间未响应，将会进入fallback代码
hystrix:
  command:
    default:
      execution:
        strategy: THREAD
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000
ribbon:
  ReadTimeout: 1500 # 请求处理的超时时间
  ConnectTimeout: 3000 # 请求连接的超时时间
  OkToRetryOnAllOperations: true # 对所有操作请求都进行重试
  MaxAutoRetries: 2 # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 2 # 切换实例的重试次数
logging:
  root: info
  com.shenjies88.eurekaclient: debug
