server:
  port: 5555
spring:
  application:
    name: eureka-gateway
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
zuul:
  routes:
    my-client:
      path: /my-client/**
      serviceId: eureka-client
# Hystrix默认的超时时间是1秒，如果超过这个时间未响应，将会进入fallback代码
hystrix:
  command:
    default:
      execution:
        strategy: THREAD
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ReadTimeout: 4000 # 请求处理的超时时间
  ConnectTimeout: 2000 # 请求连接的超时时间
  MaxAutoRetries: 0 # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 0 # 切换实例的重试次数
logging:
  root: info
  com.shenjies88.eurekagateway: debug